# ============================================================
# Workshop 003 - ETL Process using Apache Kafka + Machine Learning
# Step 04: Prepare testing data for Kafka streaming
# ============================================================

import os
import pandas as pd

from sklearn.model_selection import train_test_split


# ------------------------------------------------------------
# 1. Define project paths
# ------------------------------------------------------------

PROCESSED_DATA_PATH = "data/processed"

INPUT_FILE = os.path.join(PROCESSED_DATA_PATH, "happiness_clean.csv")
STREAM_FILE = os.path.join(PROCESSED_DATA_PATH, "happiness_stream_data.csv")


# ------------------------------------------------------------
# 2. Load clean data
# ------------------------------------------------------------

def load_clean_data():
    """
    This function loads the clean dataset generated during the ETL step.
    """

    df = pd.read_csv(INPUT_FILE)

    print("Clean dataset loaded successfully.")
    print("Dataset shape:")
    print(df.shape)

    return df


# ------------------------------------------------------------
# 3. Prepare stream dataset
# ------------------------------------------------------------

def prepare_stream_data(df):
    """
    This function prepares the test data that will be streamed through Kafka.

    We use the same feature columns used during model training.
    The actual happiness score is kept because later it allows comparison
    between the real value and the predicted value generated by the consumer.
    """

    feature_columns = [
        "gdp_per_capita",
        "social_support",
        "life_expectancy",
        "freedom",
        "generosity",
        "government_corruption",
        "year"
    ]

    target_column = "happiness_score"

    X = df[feature_columns]
    y = df[target_column]

    # Same split used in the training script: 70% train and 30% test.
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.30,
        random_state=42
    )

    stream_df = X_test.copy()
    stream_df["actual_happiness_score"] = y_test.values

    print("\nStream dataset created successfully.")
    print("Stream dataset shape:")
    print(stream_df.shape)

    return stream_df


# ------------------------------------------------------------
# 4. Save stream data
# ------------------------------------------------------------

def save_stream_data(stream_df):
    """
    This function saves the stream dataset as a CSV file.
    The Kafka producer will read this file and send each row as one message.
    """

    stream_df.to_csv(STREAM_FILE, index=False)

    print("\nStream dataset saved successfully:")
    print(STREAM_FILE)

    print("\nStream dataset preview:")
    print(stream_df.head())


# ------------------------------------------------------------
# 5. Main execution
# ------------------------------------------------------------

if __name__ == "__main__":
    happiness_data = load_clean_data()
    stream_data = prepare_stream_data(happiness_data)
    save_stream_data(stream_data)